name: desuga-poema
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
        
            - name: Add remote origin
                run: |
                    git remote add heroku https://heroku:${{ secrets.HEROKU_DESUGA_POEMA_KEY }}@git.heroku.com/${{ secrets.HEROKU_DESUGA_POEMA_NAME }}.git

            - name: Deploy to Heroku
            run: |
                git push heroku HEAD:master -f